groups:
  - name: Blackbox Alert
    rules:
      - alert: BlackboxSslCertificateWillExpireSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 10
        for: 0m
        labels:
          severity: "P3"
          severity_desc: "Moderat"
          HID: WWW0101
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/742785050"
          team: hit-opsgenie
        annotations:
          summary: "Blackbox SSL certificate will expire soon (instance {{ $labels.instance }})"
          description: "SSL certificate expires in 10 days\n  VALUE = {{ $value }}"
      - alert: BlackboxProbeFailed
        expr: probe_success == 0
        for: 0m
        labels:
          severity: "P4"
          severity_desc: "High"
          HID: WWW0102
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/1655439520"
          team: hit-opsgenie
        annotations:
          summary: "Blackbox probe failed (instance {{ $labels.instance }})"
          description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: BlackboxSlowProbe
        expr: avg_over_time(probe_duration_seconds[1m]) > 1
        for: 1m
        labels:
          severity: "P3"
          severity_desc: "Moderat"
          HID: WWW0103
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/1655865358"
          team: hit-opsgenie
        annotations:
          summary: "Blackbox slow probe (instance {{ $labels.instance }})"
          description: "Blackbox probe took more than 1s to complete\n  VALUE = {{ $value }}"
      - alert: BlackboxProbeHttpFailure
        expr: probe_http_status_code <= 199
        for: 0m
        labels:
          severity: "P4"
          severity_desc: "High"
          HID: WWW0104
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/1655865358"
          team: hit-opsgenie
        annotations:
          summary: "Blackbox probe HTTP failure (instance {{ $labels.instance }})"
          description: "HTTP status code is not 200\n  VALUE = {{ $value }}"
      - alert: BlackboxSslCertificateWillExpireSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 2
        for: 0m
        labels:
          severity: "P4"
          HID: WWW0101
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/742785050"
          team: hit-opsgenie
        annotations:
          summary: "Blackbox SSL certificate will expire soon (instance {{ $labels.instance }})"
          description: "SSL certificate expires in 2 days\n  VALUE = {{ $value }}"
      - alert: BlackboxSslCertificateExpired
        expr: probe_ssl_earliest_cert_expiry - time() <= 0
        for: 0m
        labels:
          severity: "P5"
          severity_desc: "Critical"
          HID: WWW0101
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/742785050"
          team: hit-opsgenie
        annotations:
          summary: "Blackbox SSL certificate expired (instance {{ $labels.instance }})"
          description: "SSL certificate has expired already\n  VALUE = {{ $value }}"
      - alert: BlackboxProbeSlowHttp
        expr: avg_over_time(probe_http_duration_seconds[1m]) > 1
        for: 1m
        labels:
          severity: "P3"
          severity_desc: "Moderat"
          HID: WWW0105
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/1655635988"
          team: hit-opsgenie
        annotations:
          summary: "Blackbox probe slow HTTP (instance {{ $labels.instance }})"
          description: "HTTP request took more than 1s\n  VALUE = {{ $value }}"
      - alert: BlackboxProbeSlowPing
        expr: avg_over_time(probe_icmp_duration_seconds[1m]) > 1
        for: 1m
        labels:
          severity: "P3"
          severity_desc: "Moderat"
          HID: WWW0106
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/1655635988"
          team: hit-opsgenie
        annotations:
          summary: "Blackbox probe slow ping (instance {{ $labels.instance }})"
          description: "Blackbox ping took more than 1s\n  VALUE = {{ $value }}"
