groups:
  - name: Windows Server Alert
    rules:
      - alert: WindowsServerCollectorError
        expr: windows_exporter_collector_success{collector!="iis"} == 0
        for: 0m
        labels:
          severity: "P2"
          severity_desc: "High"
          team: "hit-opsgenie"
          HID: "WSWE0101"
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/1656061978"
        annotations:
          summary: "Windows Server collector Error (instance {{ $labels.instance }})"
          description: "Collector {{ $labels.collector }} was not successful\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: WindowsServerServiceStatus
        expr: windows_service_status{status="ok"} != 1
        for: 1m
        labels:
          severity: "P2"
          severity_desc: "High"
          team: hit-opsgenie
          HID: "WSSC0101"
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/1655930925"
        annotations:
          summary: "Windows Server service Status (instance {{ $labels.instance }})"
          description: "Windows Service state is not OK\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: WindowsServerCpuUsage
        expr: 100 - (avg by (instance) (rate(windows_cpu_time_total{mode="idle"}[2m])) * 100) > 80
        for: 10m
        labels:
          severity: "P3"
          severity_desc: "Moderat"
          team: hit-opsgenie
          HID: "WSCPU0101"
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/876609545"          
        annotations:
          summary: "Windows Server CPU Usage (instance {{ $labels.instance }})"
          description: "CPU Usage is more than 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: WindowsServerMemoryUsage
        expr: 100 - ((windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes) * 100) > 90
        for: 5m
        labels:
          severity: "P3"
          severity_desc: "Moderat"
          team: hit-opsgenie
          HID: "WSCPU0101"
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/1655636009"                  
        annotations:
          summary: "Windows Server memory Usage (instance {{ $labels.instance }})"
          description: "Memory usage is more than 90%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: WindowsServerDiskSpaceUsage
        expr: 100.0 - 100 * ((windows_logical_disk_free_bytes / 1024 / 1024 ) / (windows_logical_disk_size_bytes / 1024 / 1024)) > 90
        for: 5m
        labels:
          severity: "P2"
          severity_desc: "High"
          team: hit-opsgenie
          HID: "WSRAM0101"
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/1655963670" 
        annotations:
          summary: "Windows Server disk Space Usage (instance {{ $labels.instance }})"
          description: "Disk usage is more than 90%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: WindowsServerDiskSpaceUsage
        expr: 100.0 - 100 * ((windows_logical_disk_free_bytes / 1024 / 1024 ) / (windows_logical_disk_size_bytes / 1024 / 1024)) > 80
        for: 1m
        labels:
          severity: "P3"
          severity_desc: "Moderat"
          team: hit-opsgenie
          HID: "WSHD0101"
          Help: "https://handel.atlassian.net/wiki/spaces/HITID/pages/1655963670"
        annotations:
          summary: "Windows Server disk Space Usage (instance {{ $labels.instance }})"
          description: "Disk usage is more than 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
