{
 "title": "xECM Content Server Services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": "label_values(env)" },
   {
    "name": "Service",
    "label": "Service",
    "query": "label_values(serviceExecutionTime{env=~\"$Instance\"}, serviceDisplayName)"
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "aidanmountford-html-panel", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 }, "format": "short" },
  {
   "title": "Services Overview Instance: $Instance",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "serviceAvgExecutionTime{env=~\"$Instance\"}"
    }
   ]
  },
  { "title": "$Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }, "repeat": "Service" },
  {
   "title": "Request URL",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "serviceExecutionTime{env=\"$Instance\", serviceDisplayName=\"$Service\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "serviceResponseMessage{env=~\"$Instance\", serviceDisplayName=\"$Service\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "graph",
   "description": "\n",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "serviceExecutionTime{env=~\"$Instance\", serviceDisplayName=\"$Service\"}",
     "legendFormat": "{{ env}} - {{ serviceDisplayName  }}"
    },
    {
     "expr": "avg_over_time(serviceExecutionTime{env=~\"$Instance\", serviceDisplayName=\"$Service\"}[4w]) ",
     "legendFormat": "Median {{ env }} - {{ serviceDisplayName  }}"
    }
   ]
  },
  {
   "title": "Response Bytes",
   "type": "graph",
   "description": "\n",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "serviceResponseByteCount{env=~\"$Instance\",serviceDisplayName=\"$Service\"}",
     "legendFormat": "{{ env}} - {{ serviceDisplayName  }}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "serviceResponseCode{env=~\"$Instance\", serviceDisplayName=\"$Service\"}"
    }
   ]
  },
  {
   "title": "Http Response Code",
   "type": "graph",
   "description": "\n",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "serviceResponseCode{env=\"$Instance\", serviceDisplayName=\"$Service\"}",
     "legendFormat": "{{ env }} - {{ serviceDisplayName }}"
    }
   ]
  }
 ]
}