{
 "title": "xECM Content Server General",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Instance", "query": "label_values(env)" }
  ]
 },
 "panels": [
  { "title": "General:  $Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Instance" },
  {
   "title": "perf Current Req Run Time more than 1h",
   "type": "graph",
   "description": "The amount of time in seconds that the current request has spent running. - 1.3.6.1.4.1.14876.4.2.1.1.13",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "perfCurrentReqRunTime{env=\"$Instance\"} > 3600",
     "legendFormat": "{{ env }} - {{ perfInstanceDisplayName }} - {{  infoAppContext }} "
    }
   ]
  },
  {
   "title": "Cluster Num Active Threads",
   "type": "graph",
   "description": "The number of currently active threads in this Cluster - 1.3.6.1.4.1.14876.2.1.1.8\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clusterNumActiveThreads{env=\"$Instance\"}",
     "legendFormat": "{{ env }} - {{ clusterinstanceDisplayName }}"
    },
    {
     "expr": "avg(clusterNumActiveThreads{env=\"$Instance\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "cluster Number AVG Request per Second [5min]",
   "type": "graph",
   "description": "The total number of requests serviced by this Cluster - 1.3.6.1.4.1.14876.2.1.1.10 - Request per Seconds in the last 5 Minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clusterNumReq{env=\"$Instance\"}[5m])",
     "legendFormat": "{{ env}} - {{ clusterinstanceDisplayName }}"
    },
    {
     "expr": "avg(rate(clusterNumReq{env=\"$Instance\"}[5m]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Cluster run requests average time",
   "type": "graph",
   "description": "The average run time for requests serviced by this Cluster - 1.3.6.1.4.1.14876.2.1.1.16",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "clusterRunAvgTime{env=\"$Instance\"}",
     "legendFormat": "{{ env }} - {{ clusterinstanceDisplayName }}"
    },
    {
     "expr": "avg(clusterRunAvgTime{env=\"$Instance\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Cluster Queue average  Time",
   "type": "graph",
   "description": "The average time that a request serviced by this Cluster spent queuing - 1.3.6.1.4.1.14876.2.1.1.13",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "clusterQueueAvgTime{env=\"$Instance\"}",
     "legendFormat": "{{ env }} - {{ clusterinstanceDisplayName }}"
    },
    {
     "expr": "avg(clusterQueueAvgTime{env=\"$Instance\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Cluster number Debug Exceptions",
   "type": "stat",
   "description": "The number of exceptions raised in this Cluster - 1.3.6.1.4.1.14876.2.1.1.22",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "clusterNumDebugExceptions{env=\"$Instance\"}",
     "legendFormat": "{{ clusterinstanceDisplayName }}"
    }
   ]
  }
 ]
}