modules:
  http_2xx_ipv4:
    prober: http
    timeout: 15s
    http:
      preferred_ip_protocol: ip4
  http_2xx_tomcat:
    prober: http
    timeout: 15s
    http:
      preferred_ip_protocol: ip4
      no_follow_redirects: false
      fail_if_not_ssl: true
      fail_if_body_not_matches_regexp: 
        - "Archive Server Error"
  http_2xx_xsecm:
    prober: http
    timeout: 15s
    http:
      preferred_ip_protocol: ip4
      no_follow_redirects: false
      fail_if_not_ssl: true
      fail_if_body_not_matches_regexp: 
        - "OK "
  http_2xx_otds:
    prober: http
    timeout: 15s
    http:
      preferred_ip_protocol: ip4
      no_follow_redirects: false
      fail_if_not_ssl: true
      fail_if_body_not_matches_regexp: 
        - "OpenText Directory Services Administration"
  http_2xx_otac:
    prober: http
    timeout: 15s
    http:
      preferred_ip_protocol: ip4
      no_follow_redirects: false
      fail_if_not_ssl: true
      fail_if_body_not_matches_regexp: 
        - "Open Text Monitor Web Client"
  http_2xx_otel:
    prober: http
    timeout: 15s
    http:
      preferred_ip_protocol: ip4
      no_follow_redirects: false
      fail_if_not_ssl: true
      fail_if_body_not_matches_regexp: 
        - "Web Services"
  http_2xx_ot-elib:
    prober: http
    timeout: 15s
    http:
      preferred_ip_protocol: ip4
      no_follow_redirects: false
      fail_if_not_ssl: true
      fail_if_body_not_matches_regexp: 
        - "Web Services"        
  http_2xx_otcws:
    prober: http
    timeout: 15s
    http:
      preferred_ip_protocol: ip4
      no_follow_redirects: false
      fail_if_not_ssl: true
      fail_if_body_not_matches_regexp: 
        - "Web Services"
  http_2xx_apachetomcat:
    prober: http
    timeout: 15s
    http:
      preferred_ip_protocol: ip4
      no_follow_redirects: false
      fail_if_not_ssl: true
#      fail_if_body_not_matches_regexp: 
#        - "Archive Server Error"
    
  http_2xx_otcswrdestination:
    prober: http
    timeout: 15s
    http:
      preferred_ip_protocol: ip4
      no_follow_redirects: false
      fail_if_not_ssl: true
      fail_if_body_not_matches_regexp: 
        - "objAction=Destination"       
 
  http_2xx_otcs_lb:
    prober: http
    timeout: 15s
    http:
      preferred_ip_protocol: ip4
      no_follow_redirects: false
      fail_if_not_ssl: true
      fail_if_body_not_matches_regexp: 
        - "TRUE"   
        
  http_2xx:
    prober: http
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp

